### ISSUE TITLE
Screen dimming for OLED (with solution)

### ISSUE THREAD

**Issue by ZyberSE** [elementary/wingpanel-indicator-power#60]
The built-in dimming function don't work on OLED screens, they handle it slightly different.

This works for OLED and should somehow be implemented into Elementary.

xrandr --output eDP1 --brightness 0 # fully dimmed
xrandr --output eDP1 --brightness 0.5 # half dimmed
xrandr --output eDP1 --brightness 1 # no dimming

**Comment by cassidyjames** [comment]
We don't actually manually handle any dimming, that capability is provided by GNOME Settings Daemon and lower level hardware support. In that case, manually using XRandR sounds like a bad idea as this should be supported throughout the stack, and would need to be fixed elsewhere so that it works throughout the OS.
