### ISSUE TITLE
Battery indicator is missing, instead, a "sun" icon is showing

### ISSUE THREAD

**Issue by lichenglu** [elementary/wingpanel-indicator-power#96]
Hi I am new to Elementary OS (just installed it today). Thanks for the great work!

In the wingpanel, I do not see a battery icon, instead, there is a "sun" icon for power setting (brightness can also be adjusted clicking the sun). I wonder if this is the designed behavior? Because when I see screenshots online, I can see there is a battery icon indicating the battery percentage. I have tried:

1. killed the wingpanel, and let it restart
2. reinstall switchboard-plug-power
But no luck.

I am using `elementary OS 5.0 Juno` with a `surface book 2`.
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```
Thank you in advance!

**Comment by peteruithoven** [comment]
( [The code that checks whether you have a battery](https://github.com/elementary/wingpanel-indicator-power/blob/master/src/Services/DeviceManager.vala) )

There are some relevant logs we could check, to see what is detected.
Please follow:
https://github.com/elementary/website/blob/a72876750aa97c1b4e2222eeb74e2ab80e0edb9a/docs/code/os-dev.md#wingpanel
And instead of starting wingpanel by running `wingpanel` please run it with debug logs enabled by running:
```
G_MESSAGES_DEBUG=all wingpanel 
```

Please search for "Backlight.vala:28: backlight present:" and copy it and the 10 lines following it. 
Please share those. 
I for example get the following. 
```
** (wingpanel:11152): DEBUG: 10:44:55.512: Backlight.vala:28: backlight present: true
** (wingpanel:11152): DEBUG: 10:44:55.519: DeviceManager.vala:67: Connection to UPower bus established
** (wingpanel:11152): DEBUG: 10:44:55.527: Device.vala:98: Connection to UPower device established
** (wingpanel:11152): DEBUG: 10:44:55.535: Device.vala:98: Connection to UPower device established
** (wingpanel:11152): DEBUG: 10:44:55.563: DeviceManager.vala:126: Device "/org/freedesktop/UPower/devices/line_power_AC" registered
** (wingpanel:11152): DEBUG: 10:44:55.568: Device.vala:98: Connection to UPower device established
** (wingpanel:11152): DEBUG: 10:44:55.572: DeviceManager.vala:126: Device "/org/freedesktop/UPower/devices/battery_BAT0" registered
** (wingpanel:11152): DEBUG: 10:44:55.572: Indicator.vala:117: Icon changed to "battery-full-charged-symbolic"
```

**Comment by peteruithoven** [comment]
An alternative method using the D-Feet application:
- Install D-Feet from AppCenter
- Open D-Feet
- Search for "UPower"
- Select `org.freedesktop.UPower`
- Under Object path open `/org/freedesktop/UPower`
- Open `org.freedesktop.UPower`
- Under Methods double click `EnumerateDevices` (should open popup)
- Click Execute.
- Please share the Method output. 

For comparison, I get:
```
['/org/freedesktop/UPower/devices/line_power_AC',
 '/org/freedesktop/UPower/devices/battery_BAT0']
```

**Comment by lichenglu** [comment]
@peteruithoven Thank you for the detailed reponses! 

> I'm assuming the following icon is shown?
https://github.com/elementary/icons/blob/master/status/symbolic/display-brightness-symbolic.svg

Yes, the icon shows as the one you mentioned. I will upload a img next time.

> An alternative method using the D-Feet application:
...

Mine is
```
['/org/freedesktop/UPower/devices/line_power_ADP1']
```
So I think you are right, battery for some reason cannot be found. But I am sure the battery is working appropriately. Any thoughts? Thank you!

**Comment by peteruithoven** [comment]
That's kind of a level to deep for me I'm afraid. I'd research this for linux in general, or maybe for a very popular distro like Ubuntu. I'm assuming we mostly use what Ubuntu gives us on that level. 

This issue seems relevant btw: https://github.com/jakeday/linux-surface/issues/28

I'm closing this as this is something that's out of scope for the wingpanel indicator. 

Good luck though!

**Comment by lichenglu** [comment]
@peteruithoven Thanks! I think the issue you referenced is the right place to point to, and it seems the battery stats issue is close to a solution.
